### ISSUE TITLE
Error executing miniccnx

### ISSUE THREAD

**Issue by josevl** [chesteve/mn-ccnx#14]
Hello, I have successfully build Mini-CCNx in a Ubuntu 12.04 LTS (with CCNx 0.8.2).

I have tried to recreate tutorial example (h1, h2 y r1) with miniccnxedit, but when I try to run miniccnx, it trows the following error messages:
-------------------------------------------------------
$sudo miniccnx
Parse of miniccnx.conf done.
*** Creating network
*** Adding hosts:
h1 h2 r1 
*** Adding links:
(100.00Mbit) (100.00Mbit) (h1, r1) (100.00Mbit 10 delay 1% loss) (100.00Mbit 10 delay 1% loss) (h2, r1) 
*** Configuring hosts
h1 h2 r1 
*** Adding metrics collectors:
Traceback (most recent call last):
  File "/usr/local/bin/miniccnx", line 4, in <module>
    __import__('pkg_resources').run_script('mininet==2.0.0', 'miniccnx')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.0.0-py2.7.egg/EGG-INFO/scripts/miniccnx", line 145, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.0.0-py2.7.egg/EGG-INFO/scripts/miniccnx", line 99, in execute
    
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 173, in __init__
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 352, in build
  File "build/bdist.linux-x86_64/egg/sources/metrics.py", line 249, in __init__
  File "build/bdist.linux-x86_64/egg/sources/metrics.py", line 186, in checkDatabase
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 447, in get_list_database
    return list(self.query("SHOW DATABASES").get_points())
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 317, in query
    expected_response_code=expected_response_code
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 238, in request
    raise e
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
---------------------

It seems to be the problem is in InfluxDB, but it is running ok:
$sudo /etc/init.d/influxdb status
influxd Process is running [ OK ]

Any suggestion is welcome?

**Comment by caio92** [comment]
Hello josevl,

Which version of InfluxDB are you using? Did you install the InfluxDB
Python Libraries?

Best regards,
Caio
