### ISSUE TITLE
ConfigParser.NoSectionError:

### ISSUE THREAD

**Issue by wasi0013** [chesteve/mn-ccnx#16]
I keep on getting this error when I create a topology. I'm using the virtual machine disk image( .vdi) given on the INSTALL wiki (the bz2 compressed file).
 
`Traceback (most recent call last):
  File "/usr/local/bin/miniccnx", line 5, in <module>
    pkg_resources.run_script('mininet==2.0.0', 'miniccnx')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.0.0-py2.7.egg/EGG-INFO/scripts/miniccnx", line 145, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.0.0-py2.7.egg/EGG-INFO/scripts/miniccnx", line 91, in execute
    
  File "build/bdist.linux-x86_64/egg/sources/conf_parser.py", line 303, in parse_preferences
  File "/usr/lib/python2.7/ConfigParser.py", line 347, in items
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'preferences'
`
If I add a preferences section on the miniccnx.conf error changes to 
'Value Error: Need one or more value to unpack'

Please, shed some lights on the miniccnx.conf file and tell more about what sections are must and, also formats of the sections.
Thank you!

**Comment by amuleengulati** [comment]
I am also getting the same error.  Any help would be appreciated.
