### ISSUE TITLE
Using the pre-configured VM

### ISSUE THREAD

**Issue by nilforoosh** [chesteve/mn-ccnx#17]
hello
i have installed the .vdi file of miniccnx on virtual box and i have these problems:

1- why when I run ¨sudo mn¨ command in terminal for running mininet these errors appears:

Traceback (most recent call last):
  File "/usr/local/bin/mn", line 5, in <module>
    pkg_resources.run_script('mininet==2.0.0', 'mn')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1388, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'mn'

2- when I test your configuration file for h1--s1--h2 these errors appear :

Traceback (most recent call last):
  File "/usr/local/bin/miniccnx", line 5, in <module>
    pkg_resources.run_script('mininet==2.0.0', 'miniccnx')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.0.0-py2.7.egg/EGG-INFO/scripts/miniccnx", line 145, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.0.0-py2.7.egg/EGG-INFO/scripts/miniccnx", line 91, in execute
    
  File "build/bdist.linux-x86_64/egg/sources/conf_parser.py", line 303, in parse_preferences
  File "/usr/lib/python2.7/ConfigParser.py", line 347, in items
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'preferences'

3- in miniccnxedit i can easily put hosts and routers but don´t links; how the links work in editor?
how can I  put links and join hosts and routers ?

**Comment by wasi0013** [comment]
Same here...

The 2nd error can be fixed by adding `[preferences]` in the miniccnx.conf but, after that bunch of other errors occur. i.e Section errors / Index out of range etc...

**Comment by wasi0013** [comment]
> 1- why when I run ¨sudo mn¨ command in terminal for running mininet these errors appears:
> 
> Traceback (most recent call last):
> File "/usr/local/bin/mn", line 5, in 
> pkg_resources.run_script('mininet==2.0.0', 'mn')
> File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
> self.require(requires)[0].run_script(script_name, ns)
> File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1388, in run_script
> raise ResolutionError("No script named %r" % script_name)
> pkg_resources.ResolutionError: No script named 'mn'

This error can be fixed by reinstalling mininet. However, `sudo apt-get install mininet` doesn't fix it. I just had to clone the git repo of mininet and use the command `sudo make install`
`git clone git://github.com/mininet/mininet`
`sudo make install`
This should fix the error no: 1

For the 2nd Error I modified the miniccnx.conf file like this:

`[preferences]
getMetrics: 1
ipBase: 10.0.0.0/8
metricsTimer: 30
dbPort: 8086
dbHost: localhost
dbPass: root
dbName: miniccnx_data
dbUser: root
terminalType: xterm
startCLI: 0
templatePath: miniccnx.conf
[hosts]
h2: getMetrics=1 
h1: getMetrics=1 
[routers]
s1: getMetrics=1 
[nodes]
h1: _ ccnx:/,s1
h2: _ cpu=0.1
s1: _ ccnx:/test,h2
[links]
h1:s1 bw=100
h2:s1 bw=100 loss=1 delay=10ms`
After setting it up like this I get this:
`sudo miniccnx
[sudo] password for user: 
Parse of miniccnx.conf done.
*** Creating network
*** Adding hosts:
h1 h2 s1 
*** Adding links:
(100.00Mbit) (100.00Mbit) (h1, s1) (100.00Mbit 10ms delay 1% loss) (100.00Mbit 10ms delay 1% loss) (h2, s1) 
*** Configuring hosts
h1 h2 s1 
*** Adding metrics collectors:
Host h1: database miniccnx_data already exists: appending data.
Host h2: database miniccnx_data already exists: appending data.
Host s1: database miniccnx_data already exists: appending data.
Setup time: 3

*** Done

*** Starting CLI:
miniccnx> ccndump
h1: 
h2: 
s1: 
miniccnx> `

Notice that there are no FIB entries when I used the `ccndump` command. Trying to figure out the reason why...
I will appreciate any help regarding this
@carlosmscabral  @chesteve
