### ISSUE TITLE
sudo miniccnx  No script named 'miniccnx'

### ISSUE THREAD

**Issue by gaoyanyu** [chesteve/mn-ccnx#22]
I hava installed CCNx and Miniccnx ,but when I execute the command "sudo miniccnx",error like this appears:
Traceback (most recent call last):
  File "/usr/local/bin/miniccnx", line 4, in <module>
    __import__('pkg_resources').run_script('mininet===2.3.0d1', 'miniccnx')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1644, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'miniccnx'
How can I fix it ?Anybody knows ? I will appreciat it if you could help me!!!

**Comment by ocaio** [comment]
Hello gaoyanyu,

Did you run "sudo make install"? It seems that the miniccnx package is not properly installed.

**Comment by gaoyanyu** [comment]
Hello  caio92,
Thanks for giving me help!
I run "sudo make install",and former problom dispeared,but a new one occurs like "No template file given and default template file miniccnx.conf not found. Exiting..."
And is there a need to modify the models according to the pull requests?
I am looking forward to your comments.
@caio92 #

**Comment by ocaio** [comment]
Alright, so if you are running the command **miniccnx** you need to have the config file created, so the command line interface can read it and properly start the given network. You can find examples in the folder _ccn_utils_.
However, you can try to run the command **miniccnxedit**, which will provide you a GUI to create your network, export the config file, and run it visually, which might be easier if you are not familiar with the tool.

**Comment by gaoyanyu** [comment]
Fine, thank you!
Your comment is useful for me ,and I am a green hand.I will try my best to be familiar with the tool. 
Actually,I want to emulate the in-network caching controlled by controller in SDN,so ,could you give me some advice about it ?@caio92

**Comment by Yoomif** [comment]
I using the **pre-configured VM.**

But, when I run the miniccnx command it says 

**_No template file given and default template file miniccnx.conf not found. Exiting..._**

Any one who can help me how can I solve this issues. 

I am new comer and try it for my thesis. plse help me.
